ALTER TABLE users              ADD COLUMN hlc TEXT;
ALTER TABLE users              ADD COLUMN device_id TEXT;
ALTER TABLE users              ADD COLUMN deleted_at TEXT;
ALTER TABLE users              ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE categories         ADD COLUMN hlc TEXT;
ALTER TABLE categories         ADD COLUMN device_id TEXT;
ALTER TABLE categories         ADD COLUMN deleted_at TEXT;
ALTER TABLE categories         ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE menu_items         ADD COLUMN hlc TEXT;
ALTER TABLE menu_items         ADD COLUMN device_id TEXT;
ALTER TABLE menu_items         ADD COLUMN deleted_at TEXT;
ALTER TABLE menu_items         ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ingredients        ADD COLUMN hlc TEXT;
ALTER TABLE ingredients        ADD COLUMN device_id TEXT;
ALTER TABLE ingredients        ADD COLUMN deleted_at TEXT;
ALTER TABLE ingredients        ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE recipes            ADD COLUMN hlc TEXT;
ALTER TABLE recipes            ADD COLUMN device_id TEXT;
ALTER TABLE recipes            ADD COLUMN deleted_at TEXT;
ALTER TABLE recipes            ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE inventory_logs     ADD COLUMN hlc TEXT;
ALTER TABLE inventory_logs     ADD COLUMN device_id TEXT;
ALTER TABLE inventory_logs     ADD COLUMN deleted_at TEXT;
ALTER TABLE inventory_logs     ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE tables             ADD COLUMN hlc TEXT;
ALTER TABLE tables             ADD COLUMN device_id TEXT;
ALTER TABLE tables             ADD COLUMN deleted_at TEXT;
ALTER TABLE tables             ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE orders             ADD COLUMN hlc TEXT;
ALTER TABLE orders             ADD COLUMN device_id TEXT;
ALTER TABLE orders             ADD COLUMN deleted_at TEXT;
ALTER TABLE orders             ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE order_items        ADD COLUMN hlc TEXT;
ALTER TABLE order_items        ADD COLUMN device_id TEXT;
ALTER TABLE order_items        ADD COLUMN deleted_at TEXT;
ALTER TABLE order_items        ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE order_modifiers    ADD COLUMN hlc TEXT;
ALTER TABLE order_modifiers    ADD COLUMN device_id TEXT;
ALTER TABLE order_modifiers    ADD COLUMN deleted_at TEXT;
ALTER TABLE order_modifiers    ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE payments           ADD COLUMN hlc TEXT;
ALTER TABLE payments           ADD COLUMN device_id TEXT;
ALTER TABLE payments           ADD COLUMN deleted_at TEXT;
ALTER TABLE payments           ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE shifts             ADD COLUMN hlc TEXT;
ALTER TABLE shifts             ADD COLUMN device_id TEXT;
ALTER TABLE shifts             ADD COLUMN deleted_at TEXT;
ALTER TABLE shifts             ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audit_logs         ADD COLUMN hlc TEXT;
ALTER TABLE audit_logs         ADD COLUMN device_id TEXT;
ALTER TABLE audit_logs         ADD COLUMN deleted_at TEXT;
ALTER TABLE audit_logs         ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sync_queue         ADD COLUMN hlc TEXT;
ALTER TABLE sync_queue         ADD COLUMN device_id TEXT;
ALTER TABLE sync_queue         ADD COLUMN deleted_at TEXT;
ALTER TABLE sync_queue         ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE suppliers          ADD COLUMN hlc TEXT;
ALTER TABLE suppliers          ADD COLUMN device_id TEXT;
ALTER TABLE suppliers          ADD COLUMN deleted_at TEXT;
ALTER TABLE suppliers          ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE purchase_orders    ADD COLUMN hlc TEXT;
ALTER TABLE purchase_orders    ADD COLUMN device_id TEXT;
ALTER TABLE purchase_orders    ADD COLUMN deleted_at TEXT;
ALTER TABLE purchase_orders    ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE purchase_order_items ADD COLUMN hlc TEXT;
ALTER TABLE purchase_order_items ADD COLUMN device_id TEXT;
ALTER TABLE purchase_order_items ADD COLUMN deleted_at TEXT;
ALTER TABLE purchase_order_items ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE drivers            ADD COLUMN hlc TEXT;
ALTER TABLE drivers            ADD COLUMN device_id TEXT;
ALTER TABLE drivers            ADD COLUMN deleted_at TEXT;
ALTER TABLE drivers            ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE delivery_zones     ADD COLUMN hlc TEXT;
ALTER TABLE delivery_zones     ADD COLUMN device_id TEXT;
ALTER TABLE delivery_zones     ADD COLUMN deleted_at TEXT;
ALTER TABLE delivery_zones     ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE delivery_logs      ADD COLUMN hlc TEXT;
ALTER TABLE delivery_logs      ADD COLUMN device_id TEXT;
ALTER TABLE delivery_logs      ADD COLUMN deleted_at TEXT;
ALTER TABLE delivery_logs      ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE loyalty_cards      ADD COLUMN hlc TEXT;
ALTER TABLE loyalty_cards      ADD COLUMN device_id TEXT;
ALTER TABLE loyalty_cards      ADD COLUMN deleted_at TEXT;
ALTER TABLE loyalty_cards      ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE loyalty_transactions ADD COLUMN hlc TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN device_id TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN deleted_at TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE invoices           ADD COLUMN hlc TEXT;
ALTER TABLE invoices           ADD COLUMN device_id TEXT;
ALTER TABLE invoices           ADD COLUMN deleted_at TEXT;
ALTER TABLE invoices           ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE operational_costs  ADD COLUMN hlc TEXT;
ALTER TABLE operational_costs  ADD COLUMN device_id TEXT;
ALTER TABLE operational_costs  ADD COLUMN deleted_at TEXT;
ALTER TABLE operational_costs  ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE debtors            ADD COLUMN hlc TEXT;
ALTER TABLE debtors            ADD COLUMN device_id TEXT;
ALTER TABLE debtors            ADD COLUMN deleted_at TEXT;
ALTER TABLE debtors            ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE debt_entries       ADD COLUMN hlc TEXT;
ALTER TABLE debt_entries       ADD COLUMN device_id TEXT;
ALTER TABLE debt_entries       ADD COLUMN deleted_at TEXT;
ALTER TABLE debt_entries       ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE chain_config       ADD COLUMN hlc TEXT;
ALTER TABLE chain_config       ADD COLUMN device_id TEXT;
ALTER TABLE chain_config       ADD COLUMN deleted_at TEXT;
ALTER TABLE chain_config       ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE branches           ADD COLUMN hlc TEXT;
ALTER TABLE branches           ADD COLUMN device_id TEXT;
ALTER TABLE branches           ADD COLUMN deleted_at TEXT;
ALTER TABLE branches           ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE printers           ADD COLUMN hlc TEXT;
ALTER TABLE printers           ADD COLUMN device_id TEXT;
ALTER TABLE printers           ADD COLUMN deleted_at TEXT;
ALTER TABLE printers           ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE terminals          ADD COLUMN hlc TEXT;
ALTER TABLE terminals          ADD COLUMN device_id TEXT;
ALTER TABLE terminals          ADD COLUMN deleted_at TEXT;
ALTER TABLE terminals          ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE combo_meals        ADD COLUMN hlc TEXT;
ALTER TABLE combo_meals        ADD COLUMN device_id TEXT;
ALTER TABLE combo_meals        ADD COLUMN deleted_at TEXT;
ALTER TABLE combo_meals        ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE combo_items        ADD COLUMN hlc TEXT;
ALTER TABLE combo_items        ADD COLUMN device_id TEXT;
ALTER TABLE combo_items        ADD COLUMN deleted_at TEXT;
ALTER TABLE combo_items        ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE happy_hour_rules   ADD COLUMN hlc TEXT;
ALTER TABLE happy_hour_rules   ADD COLUMN device_id TEXT;
ALTER TABLE happy_hour_rules   ADD COLUMN deleted_at TEXT;
ALTER TABLE happy_hour_rules   ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE delayed_orders     ADD COLUMN hlc TEXT;
ALTER TABLE delayed_orders     ADD COLUMN device_id TEXT;
ALTER TABLE delayed_orders     ADD COLUMN deleted_at TEXT;
ALTER TABLE delayed_orders     ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE customers          ADD COLUMN hlc TEXT;
ALTER TABLE customers          ADD COLUMN device_id TEXT;
ALTER TABLE customers          ADD COLUMN deleted_at TEXT;
ALTER TABLE customers          ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE notifications      ADD COLUMN hlc TEXT;
ALTER TABLE notifications      ADD COLUMN device_id TEXT;
ALTER TABLE notifications      ADD COLUMN deleted_at TEXT;
ALTER TABLE notifications      ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
ALTER TABLE login_sessions     ADD COLUMN hlc TEXT;
ALTER TABLE login_sessions     ADD COLUMN device_id TEXT;
ALTER TABLE login_sessions     ADD COLUMN deleted_at TEXT;
ALTER TABLE login_sessions     ADD COLUMN rev INTEGER NOT NULL DEFAULT 1;
